name: ruta
description: A lightweight and flexible backend framework for Dart, inspired by dart_frog.
version: 0.1.14
repository: https://github.com/k0zlov/ruta
homepage: https://github.com/k0zlov/ruta
license: MIT

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.19.1
  get_it: ^8.0.3
  http_parser: ^4.1.2
  injectable: ^2.5.0
  mime: ^1.0.6
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_hotreload: ^1.5.0
  shelf_static: ^1.1.3
  shelf_swagger_ui: ^2.0.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
