name: ruta
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.19.1
  get_it: ^8.0.3
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_hotreload: ^1.5.0
  shelf_static: ^1.1.3

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
